### ISSUE TITLE
Zoom in is awesome... except when you click it when you're already zoomed in

### ISSUE THREAD

**Issue by yfreemark** [stevevance/ttp-2016-transit-investments#28]
Then it zooms ALL the way out. Can we make it do nothing when you're zoomed in on it already?

**Comment by stevevance** [comment]
fixed

**Comment by yfreemark** [comment]
Unfortunately, I think this is still broken.

For example:
Zoom to Chicago, don't move the map.
Click on pace pulse.
Click on zoom in.

**Comment by stevevance** [comment]
lol, I see it. 
The problem is that I wrote my code for points, not for lines. Working on this!
